// This file was auto-generated by ML.NET Model Builder. 

using System;
using IBR_StringResourceBuilder2011ML.Model;

namespace IBR_StringResourceBuilder2011ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col0 = "ps_slk_repair2_get_inspection_delay",
                Col2 = "            PsSqlCommand cmd = new PsSqlCommand(\"",
                Col3="            PsSqlCommand cmd = new PsSqlCommand(\"",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col4 with predicted Col4 from sample data...\n\n");
            Console.WriteLine($"Col0: {sampleData.Col0}");
            Console.WriteLine($"Col2: {sampleData.Col2}");
            Console.WriteLine($"Col3: {sampleData.Col3}");
            Console.WriteLine($"\n\nPredicted Col4 value {predictionResult.Prediction} \nPredicted Col4 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
